# Local environment datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/Gym
spring.datasource.username=postgres
spring.datasource.password=programming

spring.jpa.show-sql=true
logging.level.org.gym=DEBUG
