server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Gym
spring.datasource.username=postgres
spring.datasource.password=programming
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [txId=%X{transactionId}] %-5level %logger{36} - %msg%n
